plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.21.0
        checksums:
          darwin-amd64: 03bc85164aa2d966e6d7dd692b38cc9d0c5c3a7f783c909e30378a14e95316d6
          linux-amd64: b27529dde28285884dd0c15586f8b59a25a9212aa475e32417cdf99ae5469281
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.102.0
        checksums:
          darwin-amd64: c0b565f0241bae72572acf01e742477601fbb5b0412428012677d8a0bd089634
          linux-amd64: 1bf01128bb79b9466013f4efc63b73f1c02f62f5619cce1957f7a902e65e3239
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
