plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.19.0
        checksums:
          darwin-amd64: 06679055c8072b906f6b18958bbb173a05ef813b57d77e08748e67f5e27bb8c2
          linux-amd64: df9d9dab7f6d852a1435d5cada4fcb5329b238071e7ca0e7e5e6c796bf7abaaa
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.87.0
        checksums:
          darwin-amd64: 50f605ba3b2a258a80b4e33790c996f912a9b0d3603aabef97708ea1a35a3b47
          linux-amd64: 675780ca5c11f7776adebb0da516b516203b9d1ccdd87761e2401aef9c2af655
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
