plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.22.0
        checksums:
          darwin-amd64: d7e234ced02bdf43f83d15416fc3f8d9c6fd1874ed7cecd7e0bb71e4937cc1c5
          linux-amd64: 19a616775a22b672e036e717a0a728eae14bd10af79a619dfdd7510ef2eaccb3
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.105.0
        checksums:
          darwin-amd64: 2031e1e3bb704ae2e0f9b51c0fc2a80f34fa72bda0a81f0134959319a7f57f50
          linux-amd64: bb6eeb8d7f5688c85ada28f6746b57f983d9681e8e064593b762341b40449f8f
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
