plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.32.0
        checksums:
          darwin-amd64: ed3d1f60b425b7019fe4e1da9b0a2c5ef69f5881416454ae54fa2beb476b2f79
          linux-amd64: c8f5ce8b55fd45e14845201d5003a690caffce8b75d7e8e5354c9fdeea2e32d7
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.163.0
        checksums:
          darwin-amd64: a504764e19e84451257db71ec382c00c2c2a9bc2fd752ebeffd41f898afade88
          linux-amd64: 8d39cf8b2e1e2a69835c2ad5561a9b53b1fc22267bb2771128062d8b1cbb77a1
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
