plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.13.0
        checksums:
          darwin-amd64: 052e1016abcd9c12c6cdc950271b2d05f8bba7d63e0f2061f0a42da668142044
          linux-amd64: 4c38df8de6277a6b15ed9e1eaf2448e90072ae69c74d2549abbcb64503ecaa8c
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.77.0
        checksums:
          darwin-amd64: ad9db040d8402a28060939c31151baccf7c893d6ccd07050abd95db7754d2321
          linux-amd64: e6e211e94f7cffa03b008d4743e3691bba30bb103fafb1c41b26f91e4bc93bac
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
