plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.3.0
        checksums:
          darwin-amd64: 08a65d8db9555c4580dbf6cdfd954ffafc687ecbf5a71a643bc190baa9b774ad
          linux-amd64: dda61df35df69154836b4f6caa14f88d6b1a59acdb99005e5f5de986fa33f37b
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.21.0
        checksums:
          darwin-amd64: 7c5c27d40f0800f796c155b902a41bb3ed1138f35aca93407648527955d8c5b3
          linux-amd64: 1287786175d08b4c0132cb33a1d95522fbb5e02f0ffe48d2342da9e631f3bcc8
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
