plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.10.0
        checksums:
          darwin-amd64: e434cb591c25085676cb5b8e1184754db4a870dc900f33db1bdffa3cf3bf5d05
          linux-amd64: 4df5fc92b41f2a24c17313977432e0605cdf44639d0bfe088de207a815453048
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.68.0
        checksums:
          darwin-amd64: d68334e924f0fb8629cf3fa8ddb31c3c24993f245ea52c0de68d1f33679fe91b
          linux-amd64: b3807e4d29845bb1fbc6d37283fc4a031758d37e3808b129ed72fbf3dd05e348
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
