plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.45.0
        checksums:
          darwin-amd64: 86c00f02a2fa80a2223d492e931c4ec3312b3e0c895822c2f5ed8c0ea7b2e1b9
          linux-amd64: ac50a961c95657a92105c417671b8d18dfe45da0019e72cdac0b9f5938f2ea4c
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.228.0
        checksums:
          darwin-amd64: 3880820cd5cbdf0f75f42131c4700312c3a9d1ebf1bdddd25df6162faf40758a
          linux-amd64: f555eb67f41555a8591d92fbcc40c3613ea00aa4a9fba926db2e351a9644e23c
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
    - zz_generated_refreshables.go
  paths:
    - godel
